### ISSUE TITLE
Does python-cache have different keys for different arguments on a function?

### ISSUE THREAD

**Issue by ghost** [jneen/python-cache#6]
Say I have:

```
def thing(this):
    return this
```

If I call thing() with different arguments, will it cache each one based on the argument? Or is it global for the function?

Thank you!

**Comment by jorgecarleitao** [comment]
The result depends on its arguments. The arguments must be pickable because we compute pickle them, hash them, and use the hash to check if the result was already computed.

**Comment by ghost** [comment]
Got it, thank you!
